name: Sync Fork

on:
  workflow_dispatch: # on button click
  schedule:
    - cron: '0 16 * * *'

env:
  UPSTREAM: subframe7536/maple-font
  GH_TOKEN: ${{ github.token }}

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}

      - name: Re-create the 'v-latest' tag when upstream has new tags
        run: |
          FETCH_OUTPUT=$(git remote add --fetch --tags upstream "https://github.com/${{ env.UPSTREAM }}.git" 2>&1 | tail -1)
          if [[ $FETCH_OUTPUT == ' * [new tag] '* ]]; then
            git merge upstream/$(gh repo view "${{ env.UPSTREAM }}" --json defaultBranchRef --jq '.defaultBranchRef.name')

            VERSION=${FETCH_OUTPUT#* -> v}
            sed -i "s/version \"\d+\.\d+\"/version \"${VERSION}\"/" Casks/font-maple-mono.rb

            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

            git add Casks/font-maple-mono.rb
            git commit --amend --no-edit
            git tag --force v-latest
            git push --force --tags origin main

            gh release delete v-latest --repo ${{ github.repository }} --yes
          fi
